### PR TITLE
Feature/stack tags interface

### PR DESCRIPTION
**Pull request by castodius**
Should fix https://github.com/enfogroup/aws-cdk-compliance/issues/48

I did not include all tags.

### CODE REVIEW

**Comment by castodius** [comment]
Let me know if you want me to grind through the entire list of tags we support @kabo . Figured it would be best to start with a smaller list.

**Comment by kabo** [comment]
Here's something I commonly do, perhaps could be mentioned as an example in the docs?
```ts
const { BITBUCKET_GIT_HTTP_ORIGIN, BITBUCKET_COMMIT } = process.env
const tags = {
  ...otherTags,
  LastUpdated: new Date().toISOString(),
  Repo: BITBUCKET_GIT_HTTP_ORIGIN || 'DEV_DEPLOY',
  Commit: BITBUCKET_COMMIT || 'DEV_DEPLOY',
}
```

**Comment by castodius** [comment]
Updated interface with _LastUpdated_ and _Commit_. Updated README as per the suggestion from @kabo .

**Comment by castodius** [comment]
Got verbal approval from Calle

**Comment by castodius** [comment]
While trying to make this compile using JSII we realised it will never (?) work because interfaces are restricted to camelCase. We will publish this as a stand alone package with only the interface included. In a sense this is cleaner since it will allow the StackTags interface to be used by for example a resource creating Lambda.

**Pull request closed without merging**
